version: '3'

services:
  iranvless:
    image: iranvless
    build: .
    ports:
      - 443:443
      - 80:80
    # privileged: true
    # cap_add:
    #   - NET_ADMIN
    volumes:
       - ./iranvless-panel/iranvlesspanel.db:/opt/iranvless-config/iranvless-panel/iranvlesspanel.db
       - ./ssl/:/opt/iranvless-config/ssl/
