name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
jobs:
  # test:
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       os: [ubuntu-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install project
  #       run: |
  #         sudo mkdir /opt/iranvless-config
  #         sudo cp -r * /opt/iranvless-config/
  #         cd /opt/hiddify-config/
  #         sudo bash install.sh
  #     - name: check working
  #       env:
  #         SQLALCHEMY_DATABASE_URI: sqlite:////opt/hiddify-config/iranvless-panel/database.db
  #       run: |
  #         cd /opt/iranvless-config/
  #         grep -q -e '-----Finished!-----' log/system/0-install.log 
  #         cd iranvless-panel;iranvlesspanel all-configs


  release:
    # if: startsWith(github.ref, 'refs/tags/v')
    name: Create Release
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install gitchangelog pystache
          sudo apt install -y zip
      - name: zip
        run: |
            zip -r iranvless-config.zip .  -x .**\*
      - name: Generate Changelog
        run: .github/release_message.sh > release_message.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: hiddify-config.zip
          body_path: release_message.md
    
